### ISSUE TITLE
[Question] Final variables

### ISSUE THREAD

**Issue by AllanWang** [prmr/Solitaire#17]
For consistency, shouldn't all of these be marked as final?

https://github.com/prmr/Solitaire/blob/v0.4/src/ca/mcgill/cs/stg/solitaire/model/GameModel.java#L97

https://github.com/prmr/Solitaire/blob/v0.4/src/ca/mcgill/cs/stg/solitaire/model/GameModel.java#L416

**Comment by prmr** [comment]
Yes. Fixed as part of #20.
