### ISSUE TITLE
JUnit libraries in module-info.java?

### ISSUE THREAD

**Issue by chirontt** [prmr/Solitaire#29]
@prmr 
Why are the JUnit libraries required in the application's `module-info.java` file? They should not be there in the main application's module.
https://github.com/prmr/Solitaire/blob/d189c240ee7ea2558a18b1b7c0fe5acabc70efb2/src/module-info.java#L24-L25

I've got some changes to the `.classpath` file to remove them and still make Eclipse happy. Are you interested? Or should they be left as an exercise for your students?

**Comment by prmr** [comment]
This is an expedient to keep the required config to an absolute minimum under Eclipse. Feel free to share your suggestions.

**Comment by chirontt** [comment]
PR created.
